services:
  - type: web
    name: diary-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python diary-bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
